name: Deploy to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GCP_SSH_PRIVATE_KEY }}" > ~/.ssh/authorized_keys
          chmod 600 ~/.ssh/id_rsa
          echo 35.200.178.15 > ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh Jash-HashBrown@35.200.178.15 "cd ~/Test && git pull origin main && npm install && pm2 restart index.js || pm2 start index.js"
