name: Deploy to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 35.200.178.15 >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh jash_acharya_24@35.200.178.15 "cd ~/Test && git pull origin main && npm install && pm2 restart index.js || pm2 start index.js"
